export const GET_CART = 'GET_CART';

export const ADD_PRODCUT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';

export const INCREASE_CART_PRODUCT = 'INCREASE_CART_PRODUCT';
export const DECREASE_CART_PRODUCT = 'DECREASE_CART_PRODUCT';

export const CLEAR_CART = 'CLEAR_CART';
